name: Datanim
favicon: null
layout_spectrum: 0.26665
typography_spectrum: 0.23736
title: Datanim
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.75
  lightness: 0.3148936
  saturation: 0.288167
  rhythmicContrast: 0.5
purpose: []
